# Generated by Django 5.2.16 on 2026-07-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_presence_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dnd_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
