from django.urls import path

from .enterprise_views import (
    AdminMessageDeleteView,
    AuditLogListView,
    AzureSSOView,
    CardActionView,
    CardMessageCreateView,
    CatchUpSummaryView,
    ConversationSettingsView,
    GoogleSSOView,
    MemberRoleUpdateView,
    NotificationPreferencesView,
    OffboardUserView,
    ScheduledMessageDeleteView,
    ScheduledMessageListCreateView,
    WebhookDeleteView,
    WebhookIncomingView,
    WebhookListCreateView,
)
from .views import (
    ChannelCreateView,
    ChannelJoinView,
    ChannelResourceListCreateView,
    ConversationDeleteView,
    ConversationListView,
    ConversationMediaListView,
    DirectConversationCreateView,
    GroupConversationCreateView,
    MarkConversationReadView,
    MessageAttachmentView,
    MessageDeleteView,
    MessageEditView,
    MessageListView,
    MessagePinView,
    MessageReactionToggleView,
    MessageSearchView,
    MessageUploadView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    NotificationUnreadCountView,
    PublicChannelListView,
    UserListView,
)

urlpatterns = [
    path("users/", UserListView.as_view(), name="chat-users"),
    path("search/", MessageSearchView.as_view(), name="chat-search"),
    path("preferences/notifications/", NotificationPreferencesView.as_view(), name="chat-notification-prefs"),
    path("audit-logs/", AuditLogListView.as_view(), name="chat-audit-logs"),
    path("webhooks/", WebhookListCreateView.as_view(), name="chat-webhooks"),
    path("webhooks/<int:webhook_id>/", WebhookDeleteView.as_view(), name="chat-webhook-delete"),
    path("webhooks/incoming/<str:secret>/", WebhookIncomingView.as_view(), name="chat-webhook-incoming"),
    path("admin/users/<int:user_id>/offboard/", OffboardUserView.as_view(), name="chat-offboard-user"),
    path("conversations/", ConversationListView.as_view(), name="chat-conversations"),
    path("channels/public/", PublicChannelListView.as_view(), name="chat-public-channels"),
    path("conversations/direct/", DirectConversationCreateView.as_view(), name="chat-direct-create"),
    path("conversations/group/", GroupConversationCreateView.as_view(), name="chat-group-create"),
    path("conversations/channel/", ChannelCreateView.as_view(), name="chat-channel-create"),
    path("conversations/<int:conversation_id>/join/", ChannelJoinView.as_view(), name="chat-channel-join"),
    path("conversations/<int:conversation_id>/settings/", ConversationSettingsView.as_view(), name="chat-conversation-settings"),
    path("conversations/<int:conversation_id>/catchup/", CatchUpSummaryView.as_view(), name="chat-catchup"),
    path("conversations/<int:conversation_id>/cards/", CardMessageCreateView.as_view(), name="chat-card-create"),
    path("conversations/<int:conversation_id>/scheduled/", ScheduledMessageListCreateView.as_view(), name="chat-scheduled"),
    path("conversations/<int:conversation_id>/messages/", MessageListView.as_view(), name="chat-messages"),
    path("conversations/<int:conversation_id>/media/", ConversationMediaListView.as_view(), name="chat-media"),
    path(
        "conversations/<int:conversation_id>/resources/",
        ChannelResourceListCreateView.as_view(),
        name="chat-channel-resources",
    ),
    path(
        "conversations/<int:conversation_id>/members/<int:user_id>/role/",
        MemberRoleUpdateView.as_view(),
        name="chat-member-role",
    ),
    path("conversations/<int:conversation_id>/", ConversationDeleteView.as_view(), name="chat-conversation-delete"),
    path("conversations/<int:conversation_id>/upload/", MessageUploadView.as_view(), name="chat-upload"),
    path("conversations/<int:conversation_id>/read/", MarkConversationReadView.as_view(), name="chat-mark-read"),
    path("scheduled/<int:scheduled_id>/", ScheduledMessageDeleteView.as_view(), name="chat-scheduled-delete"),
    path("messages/<int:message_id>/attachment/", MessageAttachmentView.as_view(), name="chat-message-attachment"),
    path("messages/<int:message_id>/", MessageEditView.as_view(), name="chat-message-edit"),
    path("messages/<int:message_id>/delete/", MessageDeleteView.as_view(), name="chat-message-delete"),
    path("messages/<int:message_id>/moderate/", AdminMessageDeleteView.as_view(), name="chat-message-moderate"),
    path("messages/<int:message_id>/card-action/", CardActionView.as_view(), name="chat-card-action"),
    path("messages/<int:message_id>/reactions/", MessageReactionToggleView.as_view(), name="chat-message-reactions"),
    path("messages/<int:message_id>/pin/", MessagePinView.as_view(), name="chat-message-pin"),
    path("notifications/", NotificationListView.as_view(), name="chat-notifications"),
    path("notifications/unread-count/", NotificationUnreadCountView.as_view(), name="chat-notifications-unread-count"),
    path("notifications/read-all/", NotificationMarkAllReadView.as_view(), name="chat-notifications-read-all"),
    path("notifications/<int:notification_id>/read/", NotificationMarkReadView.as_view(), name="chat-notification-read"),
]
